### PR TITLE
Fixed kubecolor coloring `oc rsh`

### LINKED ISSUE #108: oc rsh breaks when using kubecolor
# Expected Behavior

One should be able to successfully get a container shell without the presentation be screwed

# Current Behavior

I can't work when using kubecolor is set as an alias for oc command as the shell is kind of in a corrupted presentation

image

This is how it works when the alias is removed:
image

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS 14.4.1 (23E224)
* kubectl version: Client Version: 4.14.3
* kubecolor version: 0.3.0
* zsh 5.9 (arm-apple-darwin23.0.0)

### PR DESCRIPTION
**Pull request by applejag**
# Description

Disables coloring on the `rsh` subcommand, which comes from `oc rsh`.

Could change so unknown commands don't get colored at all, which could prevent this in other commands. But for now I just went with adding `rsh` as a known subcommand.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## What you changed

- Changed Subcommand to a string
- Added 'rsh' as unsupported command

## Why you think we should change it

Fixes issue for `oc` users, especially since we declare `oc` support in the README now.

## Related issue (if exists)

Closes #108

### CODE REVIEW

File: command/subcommand.go [hunk 1]
```diff
@@ -50,31 +50,29 @@ func ResolveSubcommand(args []string, config *Config) (bool, *kubectl.Subcommand
...
-	}
+	// oc (OpenShift CLI) specific subcommands
+	kubectl.Rsh: {},
+}
 
-	return true
+func isColoringSupported(sc kubectl.Subcommand) bool {
+	_, found := unsupported[sc]
+	return !found
 }
```
Comment (applejag) [inline command/subcommand.go:78]: Changing this from a slice to a map does have performance implications.

When benchmarking, a slice was as expected faster when looking up the first element in the list, but the map approach was actually faster when looking up the last element.

```console
$ go test -bench=. ./command -benchtime=5s
goos: linux
goarch: amd64
pkg: github.com/kubecolor/kubecolor/command
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
BenchmarkIsColoringSupported_rsh-8         	489333993	        16.41 ns/op
BenchmarkIsColoringSupportedMap_rsh-8      	531382500	        13.78 ns/op
BenchmarkIsColoringSupported_attach-8      	1000000000	         4.193 ns/op
BenchmarkIsColoringSupportedMap_attach-8   	680426997	         9.031 ns/op
PASS
ok  	github.com/kubecolor/kubecolor/command	29.554s
```

However the code is way smaller and in my opinion the benefit of the clean code wins over the cost of some nanoseconds (btw a nanosecond is 0.000000001 seconds)
