### PR TITLE
Fix kubectl plugins with dashes not being detected as plugins

### LINKED ISSUE #109: kubectl plugin getting colorized
Thanks for maintaining this cool project. I have a question about Krew and the statement that subcommands are not colored. In https://github.com/kubecolor/kubecolor/pull/8 this feature has been added. As far as I understand it, it looks for the path prefix kubectl- to determine if its a subcommand. But this does not work for me, as can be seen in the screenshot below. Is this a bug or is it only possible if the plugin is started directly as a script?

Example
Screenshot 2024-04-22 at 15 44 55

In my case, fzf is not able to show a preview of the output because of this.
```
DEBUG=true ./kubectl-node_connect
+ set -eou pipefail
+ IFS='
	'
+ kubecolor get pods
+ fzf
```

kubecolor 0.3.0 (Brew)
kubectl v1.30.0 (Brew)
fzf 0.50.0 (Brew)

_Originally posted by @larsgerber in https://github.com/kubecolor/kubecolor/issues/65#issuecomment-2069588063_

### PR DESCRIPTION
**Pull request by larsgerber**
# Description

Added second if statement to check whether its a subcommand with underscores instead of hyphens.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Why you think we should change it

To support the correct naming of a plugin according to the Krew Plugin Naming Guide https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/.

## Related issue (if exists)

Closes #109

### CODE REVIEW

File: kubectl/subcommand.go [hunk 1]
```diff
@@ -134,6 +134,12 @@ func InspectSubcommand(command string) (Subcommand, bool) {
 		return KubectlPlugin, true
 	}
 
+	command = strings.ReplaceAll(command, "-", "_")
+
+	if _, err := exec.LookPath("kubectl-" + command); err == nil {
+		return KubectlPlugin, true
+	}
```
Comment (applejag) [inline kubectl/subcommand.go:141]: This is very interesting, and made me question if kubectl really acts like this. And you're right, it does.

After looking at their source code and doing some testing, it seems to handle it like this:

- `kubectl do some thing`
  - try exec `kubectl-do-some-thing`
  - try exec `kubectl-do-some thing`
  - try exec `kubectl-do some thing`
- `kubectl do-some thing`
  - try exec `kubectl-do_some-thing`
  - try exec `kubectl-do_some thing`
- `kubectl do-some-thing`
  - try exec `kubectl-do_some_thing`

(Source: <https://github.com/kubernetes/kubectl/blob/d0e936c703558421df2ef367a7c8c1c5972e5c3c/pkg/cmd/cmd.go#L260-L307>)

That's super curious! I never knew!

So with that, then this code in kubecolor should also reflect these use cases.

I suggest you simpky copy-paste the kubectl `HandlePluginCommand` function, but make it return a result if it found the plugin instead of actually executing it. Probably rename it too to something like `IsPluginCommand`

And due to licensing, I suggest placing the `IsPluginCommand` in a separate file, and copy over the apache license header as well as adding a comment that you've modified the code. Adding the URL to the source file would also be preferred for good sport.

Then it'd be great with some tests showing that it works as expected.

**Review by applejag — CHANGES_REQUESTED** [review]

**Review by applejag — APPROVED** [review]
